#pragma once

#include "SFML/Window/Keyboard.hpp"

#define PI 3.14159265359

static std::map<sf::Keyboard::Key, std::string> g_key_names = {
	{sf::Keyboard::A, "A"},
	{sf::Keyboard::B, "B"},
	{sf::Keyboard::C, "C"},
	{sf::Keyboard::D, "D"},
	{sf::Keyboard::E, "E"},
	{sf::Keyboard::F, "F"},
	{sf::Keyboard::G, "G"},
	{sf::Keyboard::H, "H"},
	{sf::Keyboard::I, "I"},
	{sf::Keyboard::J, "J"},
	{sf::Keyboard::K, "K"},
	{sf::Keyboard::L, "L"},
	{sf::Keyboard::M, "M"},
	{sf::Keyboard::N, "N"},
	{sf::Keyboard::O, "O"},
	{sf::Keyboard::P, "P"},
	{sf::Keyboard::Q, "Q"},
	{sf::Keyboard::R, "R"},
	{sf::Keyboard::S, "S"},
	{sf::Keyboard::T, "T"},
	{sf::Keyboard::U, "U"},
	{sf::Keyboard::V, "V"},
	{sf::Keyboard::W, "W"},
	{sf::Keyboard::X, "X"},
	{sf::Keyboard::Y, "Y"},
	{sf::Keyboard::Z, "Z"},

	{sf::Keyboard::Num1, "1"},
	{sf::Keyboard::Num2, "2"},
	{sf::Keyboard::Num3, "3"},
	{sf::Keyboard::Num4, "4"},
	{sf::Keyboard::Num5, "5"},
	{sf::Keyboard::Num6, "6"},
	{sf::Keyboard::Num7, "7"},
	{sf::Keyboard::Num8, "8"},
	{sf::Keyboard::Num9, "9"},
	{sf::Keyboard::Num0, "0"},

	{sf::Keyboard::LControl, "Ctrl"},
	{sf::Keyboard::RControl, "Ctrl"},
	{sf::Keyboard::LAlt, "Alt"},
	{sf::Keyboard::RAlt, "Alt"},
	{sf::Keyboard::LShift, "Shift"},
	{sf::Keyboard::RShift, "Shift"},
	{sf::Keyboard::Delete, "Del"},
	{sf::Keyboard::Insert, "Ins"},
	{sf::Keyboard::Home, "Home"},
	{sf::Keyboard::PageUp, "PgUp"},
	{sf::Keyboard::PageDown, "PgDn"},
	{sf::Keyboard::Tab, "Tab"},
	{sf::Keyboard::Enter, "Enter"},
	{sf::Keyboard::Escape, "Escape"},
	{sf::Keyboard::Space, "Space"},

	{sf::Keyboard::BackSlash, "\\"},
	{sf::Keyboard::Slash, "/"},
	{sf::Keyboard::Hyphen, "-"},
	{sf::Keyboard::Equal, "="},
	{sf::Keyboard::Period, "."},
	{sf::Keyboard::LBracket, "["},
	{sf::Keyboard::RBracket, "]"},
	{sf::Keyboard::Tilde, "~"},

	{sf::Keyboard::Subtract, "Num-"},
	{sf::Keyboard::Multiply, "Num*"},
	{sf::Keyboard::Add, "Num+"},
	{sf::Keyboard::Divide, "Num/"},

	{sf::Keyboard::Numpad1, "Num1"},
	{sf::Keyboard::Numpad2, "Num2"},
	{sf::Keyboard::Numpad3, "Num3"},
	{sf::Keyboard::Numpad4, "Num4"},
	{sf::Keyboard::Numpad5, "Num5"},
	{sf::Keyboard::Numpad6, "Num6"},
	{sf::Keyboard::Numpad7, "Num7"},
	{sf::Keyboard::Numpad8, "Num8"},
	{sf::Keyboard::Numpad9, "Num9"},
	{sf::Keyboard::Numpad0, "Num0"},

	{sf::Keyboard::F1, "F1"},
	{sf::Keyboard::F2, "F2"},
	{sf::Keyboard::F3, "F3"},
	{sf::Keyboard::F4, "F4"},
	{sf::Keyboard::F5, "F5"},
	{sf::Keyboard::F6, "F6"},
	{sf::Keyboard::F7, "F7"},
	{sf::Keyboard::F8, "F8"},
	{sf::Keyboard::F9, "F9"},
	{sf::Keyboard::F10, "F10"},
	{sf::Keyboard::F11, "F11"},
	{sf::Keyboard::F12, "F12"},



};